// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NonconformityControl.Infra.Repositories;

namespace NonconformityControl.Migrations
{
    [DbContext(typeof(NonconformityContext))]
    [Migration("20200618223717_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("NonconformityControl.Models.Action", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("NonconformityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NonconformityId");

                    b.ToTable("Actions");
                });

            modelBuilder.Entity("NonconformityControl.Models.Nonconformity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Code")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("Efficient")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Nonconformities");
                });

            modelBuilder.Entity("NonconformityControl.Models.Action", b =>
                {
                    b.HasOne("NonconformityControl.Models.Nonconformity", null)
                        .WithMany("Actions")
                        .HasForeignKey("NonconformityId");
                });
#pragma warning restore 612, 618
        }
    }
}
